version: "3.9"

services:
  db:
    image: postgres:18.1
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /data/transfer/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  server:
    build: ./WebAPITransportation
    container_name: server
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: >
        Host=db;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/images:/app/images
      - ./WebAPITransportation/wait-for-postgres.sh:/app/wait-for-postgres.sh
    ports:
      - "5898:5000"
   
    depends_on:
      db:
        condition: service_healthy

  front:
    build: 
      context: ./transportation-reactts
      args:
        VITE_API_BASE_URL: ${API_URL}
    container_name: react_front
    depends_on:
      - server
    ports:
      - "3987:80"
