version: "3.9"

services:
  db:
    image: postgres:18.1
    container_name: db
    restart: always
    ports:
      - "5022:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/postgres:/var/lib/postgresql

  server:
    build: ./WebAPITransportation
    container_name: transfer_api
    volumes:
      - /data/transfer/images:/app/images
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=192.168.64.3;Database=postgres;Port=5022;Username=postgres;Password=mysecretpassword
    
    ports:
      - "5898:5000"
    depends_on:
      - db

  front:
    build: 
      context: ./transportation-reactts
    container_name: react_front
    depends_on:
      - server
    ports:
      - "3987:80"