version: "3.9"

services:
  db:
    image: postgres:18.1
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/postgres:/var/lib/postgresql/data

  server:
    build: ./WebAPITransportation
    container_name: server
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: >
        Host=db;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/images:/app/images
    ports:
      - "5898:5000"
   
    depends_on:
      - db

  front:
    build: 
      context: ./transportation-reactts
      args:
        VITE_API_BASE_URL: ${API_URL}
    container_name: react_front
    depends_on:
      - server
    ports:
      - "3987:80"